controllers/SiteController.php
<?php

namespace app\controllers;
use yii\helpers\Html;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\SenderForm;
use app\models\MyProjectForm;
use app\models\ContactForm;
use app\models\NewLabelForm;
use app\models\RegisterForm;
use app\models\NewWeekForm;
use app\models\Userkeys;
use app\models\Labels;
use app\models\DateManager;
use app\models\Project_weeks;
use yii\imagine\Image;


use app\models\User;
use app\models\Projects;
use yii\data\Pagination;
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','login', 'signup','myproject','viewweeks','newweek','editweek'],
                'rules' => [
                    [
                        'actions' => ['logout','myproject','viewweeks','newweek','editweek'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
             [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        Yii::$app->language = 'ru-RU';
        $projects = Projects::find();
        $pagination = new Pagination([
            'defaultPageSize' => 6,
            'totalCount'=>$projects->count()
        ]);
        $projects = $projects->offset($pagination->offset)->limit($pagination->limit)->all();
        return $this->render('index', [
            'projects' => $projects,
            'pagination' => $pagination
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {        
        Yii::$app->language = 'ru-RU';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
 public function actionViewweeks()
    {
        $weeks =  Project_weeks::find()
    ->where(['project_id' => Yii::$app->user->identity->project_id]);
        $pagination = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $weeks->count()
        ]);
        $weeks = $weeks->offset($pagination->offset)->limit($pagination->limit)->all();
        return $this->render('viewweek', [
            'weeks' => $weeks,
            'pagination' => $pagination
        ]);
    }
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {

        Yii::$app->user->logout();

        return $this->goHome();
    }
    public function actionEditweek() {

        $request = Yii::$app->request;
        $id = $request->get('id');  
        $number_week = $request->get('number_week');
        $week = Project_weeks::findOne([
            'project_id' => $id,
            'number_week' => $number_week
        ]);
        $form = new NewWeekForm();
        $form->loadData($week);
        $week_image = "";
        if ($form->load(Yii::$app->request->post())) {
            if ($form->validate()) {
                $form->imageMaterial = UploadedFile::getInstances($form, 'imageMaterial');
                foreach ($form->imageMaterial as $file) {
                    $name = uniqid() . '.' . $file->extension;
                    $file->saveAs('week_image/' .   $name . '.');
                    $week_image = $week_image.$name.','; 
                }
                if ($week_image!="") {
                    $week->image_week = $week_image;
                }
                $countWeek = $this->countWeeks(Yii::$app->user->identity->project_id); 
                $week->project_id = Yii::$app->user->identity->project_id;
                $week->number_week=$countWeek+1;
                $form->saveData($week);
                return $this->render('about');
            }
            else {
           
        }
            } 
        return $this->render('newweek',['form'=> $form]);
    }
      public function actionNewlabel() {

       $id =  Yii::$app->user->identity->project_id;
        $form = new NewLabelForm();
      
        if ($form->load(Yii::$app->request->post())) {
            if ($form->validate()) {
                $label = new Labels();
                $label->project_id = $id;
                $form->saveData($label);
                return $this->render('about');
            }
            else {
           
        }
            } 
        return $this->render('newlabel',['form'=> $form]);
    }
  public function actionViewproject()
    {

        $request = Yii::$app->request;
        $id = $request->get('id');  
        $project = Projects::findOne([
        'id' => $id,
        ]);
        $weeks =  Project_weeks::find()
        ->where(['project_id' => $id]);
        $labels =  Labels::find()->where(['project_id' => $id])->all();;
        $pagination = new Pagination([
            'defaultPageSize' => 3,
            'totalCount'=>$weeks->count()
        ]);
        $weeks = $weeks->offset($pagination->offset)->limit($pagination->limit)->all();
        $labels = DateManager::sortDates($labels);
        return $this->render('view_project',[
            'project' => $project,
            'weeks' => $weeks,
            'pagination'=> $pagination,
            'labels' => $labels
        ]);
 
    }
    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {

        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
public function actionChat() {

               return $this->render('chat');

}
    public function actionAbout()
    {

        return $this->render('about');
    }
    public function actionRegistration()
    {

      $form = new RegisterForm();  
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
        //сохранение данных в бд 
           $form->registrationUser();
           return $this->render('about');

        }
            
         else {
        
        }
        return $this->render('registration', [
            'form' => $form,
     
        ]);
    }
    
//    public function actionSendproject() {
//        $form = new SenderForm();
//        $form->file = UploadedFile::getInstance($form,'file');
//
//        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
//            $form->file = UploadedFile::getInstance($form,'file');
//            $form->file->saveAs(Yii::$app->params['pathUploads'] .'files/'.$form->file->baseName.".".$form->file->extension);
//        } 
//        return $this->render('send_project',['form'=> $form]);
//    }
    private function countWeeks($project_id) {

        return  Project_weeks::find()
    ->where(['project_id' => $project_id])
    ->count();
    }   
    
    public function actionNewweek() {

        $form = new NewWeekForm();
         $week = new Project_weeks();
        $week->image_week ="";
            if ($form->load(Yii::$app->request->post())) {
                if ($form->validate()) {
                     $form->imageMaterial = UploadedFile::getInstances($form, 'imageMaterial');

                  foreach ($form->imageMaterial as $file) {
                      $name = uniqid() . '.' . $file->extension;
                $file->saveAs(Yii::$app->params['pathUploads'] . 'week_image/' .   $name . '.');
                    $week->image_week = $week->image_week.$name.','; 
            }
               
                $countWeek = $this->countWeeks(Yii::$app->user->identity->project_id); 
                $week->project_id = Yii::$app->user->identity->project_id;
                $week->number_week=$countWeek+1;
                $form->saveData($week);
                        return $this->render('about');
                }
                 else {
           
        }
        }
        return $this->render('newweek',['form'=> $form]);
    }
     public function actionViewlabels() {
          
         $labels =  Labels::find()
    ->where(['project_id' => Yii::$app->user->identity->project_id]);
        $pagination = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $labels->count()
        ]);
        $labels = $labels->offset($pagination->offset)->limit($pagination->limit)->all();
        return $this->render('viewlabels', [
            'labels' => $labels,
            'pagination' => $pagination
        ]);
        
    }   
    public function actionEditlabel() {
         $request = Yii::$app->request;
        $id = $request->get('id');  
        $label = Labels::findOne([
            'id' => $id,

views/site/chat.php
<?php
use yii\widgets\LinkPager;
use Imagine\Image\Box;

use app\models\User;
?>
<?php echo \sintret\chat\ChatRoom::widget([
            'url' => \yii\helpers\Url::to(['/chat/send-chat']),
            'userModel'=>  \app\models\User::className(),
            'userField' => 'avatarImage'
]); ?>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
Спасибо, что решили связаться с нами. Мы ответим так быстро, как только сможем
    </div>

     

    <?php else: ?>

        <p>
            Если вы хотите отправить отзыв или предложение о работе сайта, воспользуйтесь данной формой
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true])->label("Ваше имя") ?>

                    <?= $form->field($model, 'email')->label("Ваш e-mail") ?>

                    <?= $form->field($model, 'subject')->label("Тема письма") ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6])->label("Текст письма") ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\widgets\LinkPager;
use Imagine\Image\Box;

use app\models\User;
?>
<style>

.card-project a {
    color: #000 !important;
    text-decoration: none !important;
}
</style>


       <h1 class="header-text">Проекты</h1>
   <div class="container-fluid">
    
         <?php for($i = 0; $i < count($projects); $i+=2) {?>
<div class="row">
                 <?php for($j = $i; $j < count($projects) && $j<$i+2; $j++) {?>

            <div class="col-md-5 col-md-offset-1" >
                <div class="well bs-component card-project">
                    <a href=<?=Yii::$app->getUrlManager()->createUrl(['site/viewproject','id' => $projects[$j]->id ])?>>
                    <div class="card-image border-tlr-radius">
                        
                        <img src="files/<?=$projects[$j]->image?>"></img>
                    </div>
                    <p class="title"><b><?=$projects[$j]->name?></b></p>
                    <?php
                        if ($projects[$j]->is_complete==0) {
                            ?><p class="status-inwork"><b>В процессе</b></p><?php
                        } else {
                            ?> <p class="status-all"><b>Закончен</b></p> <?php
                        }
                    ?>
                    <div class="text-project">
                    <p><?=$projects[$j]->short_describe?></p>
                 
                </div>
                    </a>
            </div>
            
       </div>

    <?php }?>
</div>

<?php }?>
     
</div>
<?= LinkPager::widget(['pagination' => $pagination]) ?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста заполните следующие данные, чтобы зайти на сайт:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput()->label("Пароль") ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ])->label("Запомнить меня") ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

   
</div>

views/site/my_project.php
<?php
use yii\helpers\Html;
use  yii\bootstrap\ActiveForm;
use app\models\ChatWidget;
?>
<style>
    .chat-container {
            padding-top: 5%;
                    padding-bottom: 5%;

    }
    .chat-text {
        text-align: center;
    }
</style>
<?php $f = ActiveForm::begin(['options' =>['enctype' => 'multipart/form-data']]); ?>

<?=$f->field($form, 'name')->label('Название проекта'); ?>

<?=$f->field($form, 'target')->label('Цель проекта'); ?>
<?=$f->field($form, 'problems')->textArea(['rows' => 4, 'enableLabel' => true])->label('Задачи проекта'); ?> 
<?=$f->field($form, 'shortDescribe')->textArea(['rows' => 4, 'enableLabel' => true])->label('Краткое описание проекта(не более 100 слов)'); ?> 
<?=$f->field($form, 'describe')->textArea(['rows' => 6, 'enableLabel' => true])->label('Описание'); ?> 
<?=$f->field($form, 'authors')->textArea(['rows' => 6, 'enableLabel' => true])->label('Авторы проекта'); ?>
<?=$f->field($form, 'contactMail')->label('Контактный e-mail проекта'); ?>
<?= $f->field($form, 'file')->fileInput()->label('Загрузить изображение'); ?>
<?=$f->field($form, 'linkVideo')->label('Видео проекта(ссылка на YouTube)'); ?>
 <?= $f->field($form, 'visibleMail')->checkbox()->label('Показывать пользователям вашу почту'); ?>
 <?= $f->field($form, 'visibleAuthor')->checkbox()->label('Показывать пользователям имя автора проекта'); ?>
<a></a>
<?=Html::submitButton('Сохранить',['class' => 'btn btn-primary', 'name' => 'login-button']); ?>
<?php ActiveForm::end(); ?>
<h4>Дневник разработки</h4>
<br>
<p>Дневник разработки нужен для рассказа о каждом этапе развития проекта. Каждую неделю добавляйте новую запись в дневник разработки для рассказа, что вы успели за нее сделать и что планируете делать дальше</p>
<a style = "margin: 5px"  href= <?=Yii::$app->getUrlManager()->createUrl(['site/newweek'])?>>Добавить новую запись в дневник разработки</a> 
<br>
<a style = "margin: 5px"  href= <?=Yii::$app->getUrlManager()->createUrl(['site/viewweeks'])?>>Посмотреть все недели проекта</a> 
<br>
<h4>Временная линия</h4>
<br>
<p>Временная линия показывает, что и к какому сроку вы планируете сделать</p>
<a style = "margin: 5px"  href= <?=Yii::$app->getUrlManager()->createUrl(['site/newlabel'])?>>Добавить новую метку на временную линию</a> 
<br>
<a style = "margin: 5px"  href= <?=Yii::$app->getUrlManager()->createUrl(['site/viewlabels'])?>>Посмотреть все метки проекта</a> 
<br>
<div class="container chat-container">
<div class="row">
    
    <div class="col-md-12 chat-text"><h3>Чат участников проекта</h3></div>    
</div>
<?= ChatWidget::widget() ?>
    
    </div>


views/site/newlabel.php
<?php
use yii\helpers\Html;
use  yii\bootstrap\ActiveForm;
   
use kartik\date\DatePicker;
?>

<?php $f = ActiveForm::begin(); ?>
<?=$f->field($form, 'title')->textInput(['enableLabel' => true])->label('Название метки'); ?>

<?=$f->field($form, 'description')->textArea(['rows' => 3, 'enableLabel' => true])->label('Опишите, что к этому времени должно быть готово'); ?>
<?=$f->field($form, 'date1')->widget(DatePicker::classname(), [
    'options' => ['placeholder' => 'Вставьте дату для метки'],
    'pluginOptions' => [
        'autoclose'=>true,
        'format' => 'dd-mm-yyyy'

    ]
]); ?>

<?=Html::submitButton('Сохранить',['class' => 'btn btn-primary', 'name' => 'login-button']); ?>
<?php ActiveForm::end(); ?>

views/site/newweek.php
<?php
use yii\helpers\Html;
use  yii\bootstrap\ActiveForm
   
?>

<?php $f = ActiveForm::begin(['options' =>['enctype' => 'multipart/form-data']]); ?>
<?=$f->field($form, 'titleWeek')->textInput(['enableLabel' => true])->label('Название недели'); ?>

<?=$f->field($form, 'newMaterial')->textArea(['rows' => 6, 'enableLabel' => true])->label('Опишите, что в проект за неделю было добавлено нового'); ?>
<?=$f->field($form, 'plannedMaterial')->textArea(['rows' => 6, 'enableLabel' => true])->label('Опишите, что вы планируете добавить в проект на следующей неделе'); ?>
<?=$f->field($form, 'imageMaterial[]')->fileInput(['multiple' => true])->label('Загрузить изображения(максимум 4 штуки)'); ?>

<?=Html::submitButton('Сохранить',['class' => 'btn btn-primary', 'name' => 'login-button']); ?>
<?php ActiveForm::end(); ?>

views/site/registration.php
<?php
use yii\helpers\Html;
use  yii\bootstrap\ActiveForm
   
?>
<?php $f = ActiveForm::begin(); ?>
<!--<?= $f->errorSummary($form); ?>-->


<?=$f->field($form, 'key1')->label('Ключ для регистрации'); ?>
<?=$f->field($form, 'name')->label('Имя пользователя'); ?>
<?=$f->field($form, 'email')->label('E-mail'); ?>
<?=$f->field($form, 'password')->passwordInput()->label('Пароль'); ?>
<?=$f->field($form, 'password_repeat')->passwordInput()->label('Повторите пароль'); ?>
<?=Html::submitButton('Зарегистрироваться',['class' => 'btn btn-primary', 'name' => 'login-button']); ?>

<?php ActiveForm::end(); ?>

views/site/send_project.php
<?php
use yii\helpers\Html;
use  yii\bootstrap\ActiveForm
   
?>
 <?php if ($key) { ?>
 <?php } ?>
<?php $f = ActiveForm::begin(['options' =>['enctype' => 'multipart/form-data']]); ?>
<?=$f->field($form, 'name'); ?>
<?=$f->field($form, 'email'); ?>
<?=$f->field($form, 'file')->fileInput(); ?>

<?=Html::submitButton('Зарегистрироваться'); ?>

<?php ActiveForm::end(); ?>

views/site/viewlabels.php
<?php
use yii\widgets\LinkPager;
use Imagine\Image\Box;

use app\models\User;
?>
<style>

.week-card a {
    color: #000 !important;
    text-decoration: none !important;
}
</style>
<div class="container-fluid">
<?php
    for ($i = 0; $i <count($labels); $i++) {
    ?>
    <div class="row">
           <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="card week-card">
                <a href=<?=Yii::$app->getUrlManager()->createUrl(['site/editlabel','id' => $labels[$i]->id])?>>
             <div class="container">
                <h4>
                 <?= $labels[$i]->title ?>
                 
                 </h4> 
                
                </div>
                </a>
             </div> 
           </div>
    </div>
    <?php
    }
    ?>
   
  
<?= LinkPager::widget(['pagination' => $pagination]) ?> 
</div>

views/site/viewweek.php
<?php
use yii\widgets\LinkPager;
use Imagine\Image\Box;

use app\models\User;
?>
<style>

.week-card a {
    color: #000 !important;
    text-decoration: none !important;
}
</style>
<div class="container-fluid">
<?php
    for ($i = 0; $i <count($weeks); $i++) {
    ?>
    <div class="row">
           <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="card week-card">
                <a href=<?=Yii::$app->getUrlManager()->createUrl(['site/editweek','id' =>$weeks[$i]->project_id,'number_week' => $weeks[$i]->number_week ])?>>
             <div class="container">
                <h4>
                 Неделя #<?=$weeks[$i]->number_week ?>. <?=$weeks[$i]->title_week ?>
                 
                 </h4> 
                
                </div>
                </a>
             </div> 
           </div>
    </div>
    <?php
    }
    ?>
   
  
<?= LinkPager::widget(['pagination' => $pagination]) ?> 
</div>